#!/usr/bin/env bash
# One-command local setup: writes agents/text_voice/.env from Secret Manager.
#
# A new developer runs this once and can dial immediately — no key is emailed,
# pasted into chat, or committed. Requires only Secret Manager READ access
# (roles/secretmanager.secretAccessor), which every dev already has.
#
#   cd agents/text_voice && ./setup_env.sh
#
# Re-run it any time a key is rotated; it overwrites .env in place.

set -euo pipefail
cd "$(dirname "$0")"

PROJECT="${GOOGLE_CLOUD_PROJECT:-ldqfingsrv-dev}"
ENV_FILE=".env"

command -v gcloud >/dev/null || { echo "ERROR: gcloud not on PATH"; exit 1; }
gcloud auth application-default print-access-token >/dev/null 2>&1 \
  || { echo "ERROR: no ADC. Run: gcloud auth application-default login"; exit 1; }

fetch() {  # <secret-name>
  gcloud secrets versions access latest --secret="$1" --project="$PROJECT" 2>/dev/null \
    || { echo "ERROR: cannot read secret '$1' in $PROJECT." >&2
         echo "       Ask an admin to create it, or check your IAM role." >&2
         exit 1; }
}

echo "Fetching secrets from $PROJECT ..."
VAPI_KEY="$(fetch lqabr-vapi-api-key)"
ANTHROPIC_KEY="$(fetch lqabr-anthropic-api-key)"

[ -f "$ENV_FILE" ] && cp "$ENV_FILE" "${ENV_FILE}.bak" && echo "  (existing .env backed up to ${ENV_FILE}.bak)"

cat > "$ENV_FILE" <<EOF
# GENERATED by setup_env.sh — do not commit (git-ignored).
# Re-run ./setup_env.sh to refresh after a key rotation.

LQABR_TEXT_VOICE_MODEL=anthropic/claude-sonnet-5
ANTHROPIC_API_KEY=${ANTHROPIC_KEY}

LQABR_MCP_BASE_URL=http://localhost:8080/mcp

LQABR_VAPI_API_KEY=${VAPI_KEY}
LQABR_VAPI_PHONE_NUMBER_ID=e4a65189-cede-4207-a7a7-50431102136e
LQABR_VAPI_ASSISTANT_ID=4f00be12-203d-468f-a11d-f45798165983

GOOGLE_CLOUD_PROJECT=${PROJECT}
LQABR_SENDER_NAME=the LQABR team
LQABR_LOG_JSON=1
LQABR_LOG_LEVEL=INFO
EOF

chmod 600 "$ENV_FILE"
echo "Wrote $ENV_FILE ($(grep -c '=' "$ENV_FILE") variables). You're ready:"
echo "  cd src && uvicorn tools:app --port 8082"
