#!/usr/bin/env bash
# One-command local setup: writes agents/research/.env from Secret Manager.
#
# A new developer runs this once and can run a campaign immediately — no key is
# emailed, pasted into chat, or committed. Requires only Secret Manager READ
# access (roles/secretmanager.secretAccessor), which every dev already has.
#
#   cd agents/research && ./setup_env.sh          # writes are OFF (dry run)
#   cd agents/research && ./setup_env.sh --live   # writes are ON
#
# Re-run it any time a key is rotated; it overwrites .env in place.

set -euo pipefail
cd "$(dirname "$0")"

PROJECT="${GOOGLE_CLOUD_PROJECT:-ldqfingsrv-dev}"
ENV_FILE=".env"
MCP_URL="${LQABR_RESEARCH_MCP_BASE_URL:-http://localhost:8080/mcp}"

DRY_RUN=1
case "${1:-}" in
  --live) DRY_RUN=0 ;;
  --dry-run|"") DRY_RUN=1 ;;
  *) echo "usage: $0 [--live|--dry-run]"; exit 2 ;;
esac

command -v gcloud >/dev/null || { echo "ERROR: gcloud not on PATH"; exit 1; }
gcloud auth application-default print-access-token >/dev/null 2>&1 \
  || { echo "ERROR: no ADC. Run: gcloud auth application-default login"; exit 1; }

fetch() {  # <secret-name>
  gcloud secrets versions access latest --secret="$1" --project="$PROJECT" 2>/dev/null \
    || { echo "ERROR: cannot read secret '$1' in $PROJECT." >&2
         echo "       Ask an admin to create it, or check your IAM role." >&2
         exit 1; }
}

echo "Fetching secrets from $PROJECT ..."
ANTHROPIC_KEY="$(fetch lqabr-anthropic-api-key)"

# An empty key is the failure this script exists to prevent: the agent starts
# fine and every lead then dies at the research step with "ANTHROPIC_API_KEY is
# not set". Catch it here, where the message can say what to do about it.
[ -n "$ANTHROPIC_KEY" ] || {
  echo "ERROR: lqabr-anthropic-api-key came back empty in $PROJECT." >&2
  echo "       The agent would start and fail on every lead. Not writing .env." >&2
  exit 1
}

# The HubSpot token is deliberately NOT written here. The agent resolves it at
# run time from Secret Manager by NAME (see hubspot_direct.py + secrets.py), so
# the credential never lands on disk and a rotation needs no local change.

[ -f "$ENV_FILE" ] && cp "$ENV_FILE" "${ENV_FILE}.bak" \
  && echo "  (existing .env backed up to ${ENV_FILE}.bak)"

cat > "$ENV_FILE" <<EOF
# GENERATED by setup_env.sh — do not commit (git-ignored).
# Re-run ./setup_env.sh to refresh after a key rotation.

# ── model ────────────────────────────────────────────────────────────────
LQABR_RESEARCH_MODEL=claude-sonnet-4-6
ANTHROPIC_API_KEY=${ANTHROPIC_KEY}

# ── MCP: the only door to HubSpot for reads and writes ───────────────────
# The container must be up before the agent starts, or the boot check warns.
LQABR_RESEARCH_MCP_BASE_URL=${MCP_URL}

# ── HubSpot ──────────────────────────────────────────────────────────────
# The token is fetched at run time BY NAME, never stored here.
LQABR_RESEARCH_SECRETS_SOURCE=secret_manager
LQABR_RESEARCH_GCP_PROJECT=${PROJECT}
LQABR_RESEARCH_HUBSPOT_TOKEN_SECRET=lqabr-hubspot-access-token
LQABR_RESEARCH_HUBSPOT_CONTEXT_PROPERTY=lead_context

# 1 = compute and log the write, never send it. 0 = write to real contacts.
LQABR_RESEARCH_DRY_RUN=${DRY_RUN}
# 0 = a re-run overwrites existing context. 1 = makes a campaign resumable.
LQABR_RESEARCH_SKIP_IF_CONTEXT_PRESENT=0

# ── logging ──────────────────────────────────────────────────────────────
# auto = readable on a terminal, JSON when piped or on Cloud Run.
LQABR_RESEARCH_LOG_FORMAT=auto
LQABR_RESEARCH_LOG_LEVEL=INFO
LQABR_RESEARCH_LOG_FILE=logs/agents/research/agent.log
EOF

chmod 600 "$ENV_FILE" 2>/dev/null || true

# Report the mode we actually got, not the one we asked for. On a Windows drive
# mounted into WSL (/mnt/c) DrvFs ignores chmod, so 600 silently stays 777 —
# claiming otherwise would be a false assurance about a file holding a key.
MODE="$(stat -c '%a' "$ENV_FILE" 2>/dev/null || echo '?')"
echo "Wrote $ENV_FILE ($(grep -c '^[A-Z]' "$ENV_FILE") variables), mode ${MODE}."
if [ "$MODE" != "600" ]; then
  echo "  NOTE: could not restrict permissions (mode ${MODE})."
  case "$(pwd -P)" in
    /mnt/*) echo "        This is a Windows drive mounted in WSL; DrvFs ignores chmod." ;;
  esac
  echo "        The file holds a live API key — treat it accordingly."
fi
echo

if [ "$DRY_RUN" = "1" ]; then
  echo "  WRITES ARE OFF (LQABR_RESEARCH_DRY_RUN=1)."
  echo "  Nothing reaches HubSpot. Re-run with --live, or edit .env, when ready."
else
  echo "  *** WRITES ARE LIVE (LQABR_RESEARCH_DRY_RUN=0). ***"
  echo "  A campaign overwrites lead_context on real contacts."
fi

cat <<'EOF'

Start it:
  source .env is NOT enough on its own — see the ordering note below.

  cd agents/research
  set -a && source .env && set +a
  python -m uvicorn service_app:app --port 8086 --app-dir src

  Order matters: sourcing .env AFTER exporting a variable overwrites it.
  Everything this agent needs is in .env, so source it FIRST.

Check it:
  curl -s localhost:8086/health   | python3 -m json.tool   # dry_run, MCP, tools
  curl -s localhost:8086/mcp/tools | python3 -m json.tool  # names vs the server
EOF
